// src/components/GodotGame.jsx
import React from 'react';

// The path to the HTML file generated by Godot.
const GODOT_GAME_URL = '/godot-game/index.html';

export default function GodotGame() {
  return (
    // A container to control the size and centering of the iframe
    <div style={{
      width: '100%',
      height: '100%',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    }}>
      <iframe
        title="godot-game"
        src={GODOT_GAME_URL}
        style={{
          width: '90vw',    // Use viewport width for responsiveness
          height: '90vh',   // Use viewport height
          border: 'none',   // Remove the default iframe border
        }}
      />
    </div>
  );
}
